
# OMITIR SIEMPRE PRIMERA COLUMNA

In [14]:
import pandas as pd

def safe_read_csv(path):
    """Read CSV robustly: tries common encodings/separators and skips malformed rows."""
    last_error = None
    for encoding in ("utf-8", "utf-8-sig", "latin1"):
        for sep in (",", ";"):
            try:
                return pd.read_csv(path, encoding=encoding, sep=sep, engine="python", on_bad_lines="skip")
            except Exception as err:
                last_error = err
    raise last_error

In [15]:

print("Este es el df1 -> PerdidaDeBecas.csv")


df1 = safe_read_csv("datos_raw/personas/PerdidaDeBecas.csv")
df1.head()
# Convocatoria,region,Descripcion,Resolucion_Ret_Beca,Fec_Resolucion_Ret_Beca,Fec_Postulacion,TipoInstitucion,InstitucionEducativa,InstitucionSede,CarreraDescripcion,Genero,FECHA_HORA

Este es el df1 -> PerdidaDeBecas.csv

,1,Beca Perú (Lima - Callao) 2014-02,LIMA,Becarios que abandonaron los estudios (No recibieron subvencion),RESOLUCION JEFATURAL,2015-08,2014-06,Instituto de Educación Superior,IES PRIVADO PERUANO DE SISTEMAS SISE,SEDE CERCADO DE LIMA,COMUNICACION AUDIOVISUAL,MASCULINO,14/04/2026 14:01:19
0,2,CREDITO CONTINUIDAD 2020,LIMA,Becarios con suspension,RESOLUCION JEFATURAL,2021-05,2020-07,Universidad,UNIVERSIDAD CIENTIFICA DEL SUR,SEDE VILLA EL SALVADOR,INGENIERIA AMBIENTAL,FEMENINO,14/04/2026 14:01:19
1,3,Beca Presidente de la República 2017,ESPAÑA,Becarios declarados nulos,NaN,NaN,2017-05,Universidad,UNIVERSIDAD DE BARCELONA,SEDE BARCELONA,MASTER OFICIAL EN PLANIFICACION TERRITORIAL Y ...,FEMENINO,14/04/2026 14:01:19
2,4,Beca de Continuidad de Estudios 2020,CUSCO,Becarios declarados nulos,NaN,NaN,2020-06,Instituto de Educación Superior,IES PRIVADO KHIPU,SEDE SAN SEBASTIAN,ADMINISTRACION DE NEGOCIOS INTERNACIONALES,FEMENINO,14/04/2026 14:01:19
3,5,Beca de Permanencia de Estudios - Nacional 201...,AREQUIPA,Becarios declarados nulos,NaN,2017-02,2016-07,Universidad,UNIVERSIDAD NACIONAL DE SAN AGUSTIN DE AREQUIPA,SEDE AREQUIPA,INGENIERIA DE MINAS,MASCULINO,14/04/2026 14:01:19
4,6,Presidente de la República 2013-04,ARGENTINA,Becarios declarados nulos,NaN,2014-12,2013-11,Universidad,UNIVERSIDAD DE BUENOS AIRES,SEDE BUENOS AIRES,MAESTRIA EN SALUD ANIMAL,FEMENINO,14/04/2026 14:01:19

In [16]:

print("Este es el df2 -> NotaPromedioDelPostulantePorRegion.csv")


df2 = safe_read_csv("datos_raw/personas/NotaPromedioDelPostulantePorRegion.csv")
df2.head()

# Region, Promedio, Modalidad, Anio_Convocatoria, TipoInstitucion, InstitucionEducativa, Semestre, FECHA_HORA

Este es el df2 -> NotaPromedioDelPostulantePorRegion.csv

,1,CUBA,4,000000,Modalidad Pregrado Internacional,2013,Unnamed: 6,Unnamed: 7,2013-I,14/04/2026 14:01:21
0,2,LIMA,14,500000,Albergue,2015,Universidad,UNIVERSIDAD PRIVADA SAN IGNACIO DE LOYOLA,2015-I,14/04/2026 14:01:21
1,3,LIMA,12,0,Beca Excelencia Academica,2014,Universidad,PONTIFICIA UNIVERSIDAD CATOLICA DEL PERU,2016-I,14/04/2026 14:01:21
2,4,LIMA,13,0,Beca Peru,2013,Instituto de Educación Superior,IES PRIVADO FREDERICK WINSLOW TAYLOR,2012-I,14/04/2026 14:01:21
3,5,LIMA,11,0,Beca Peru,2013,Instituto de Educación Superior,IES PRIVADO FREDERICK WINSLOW TAYLOR,2012-II,14/04/2026 14:01:21
4,6,LIMA,15,0,Beca Vocacion Maestro,2014,Universidad,PONTIFICIA UNIVERSIDAD CATOLICA DEL PERU,2016-I,14/04/2026 14:01:21

In [17]:

print("Este es el df3 -> EstadosDelBecario.csv")

df3 = safe_read_csv("datos_raw/personas/EstadosDelBecario.csv")
df3.head()

# Estado, Condicion, Causal, FECHA_HORA

Este es el df3 -> EstadosDelBecario.csv

,1,ACTIVO,REGULAR,SIN OBSERVACION,14/04/2026 14:01:22
0,2,ACTIVO,REGULAR,BECARIOS OBSERVADOS Y/O EN REGULARIZACION,14/04/2026 14:01:22
1,3,ACTIVO,SUSPENDIDO,BECARIOS CON SUSPENSION,14/04/2026 14:01:22
2,4,ACTIVO,OBSERVADO,BECARIOS OBSERVADOS Y/O EN REGULARIZACION,14/04/2026 14:01:22
3,5,ACTIVO,EX-BECARIO,BECARIO EGRESADO APROBADO,14/04/2026 14:01:22
4,6,INACTIVO,REGULAR,BECARIOS QUE RENUNCIARON,14/04/2026 14:01:22

In [18]:

print("Este es el df4 -> Credito18Postulacion.csv")

df4 = safe_read_csv("datos_raw/personas/Credito18Postulacion.csv")
df4.head()

# Convocatoria, TipoInstitucion, InstitucionEducativa, InstitucionSede, Descripcion, EstadoCredito18, Periodo_Postulacion, Period_registro_postulac, Period_anulacion, UbigeoLocalidad, FECHA_HORA

Este es el df4 -> Credito18Postulacion.csv

,1,1era. convocatoria,Universidad,PONTIFICIA UNIVERSIDAD CATOLICA DEL PERU,SEDE SAN MIGUEL,ARQUITECTURA,REGISTRO COMPLETO,2016-01,2016-01.1,Unnamed: 9,CALLAO,14/04/2026 14:01:19
0,2,2da. convocatoria,Universidad,PONTIFICIA UNIVERSIDAD CATOLICA DEL PERU,SEDE SAN MIGUEL,ARQUITECTURA,REGISTRO COMPLETO,2016-08,2016-08,2016-08,BREÑA,14/04/2026 14:01:19
1,3,2da. convocatoria,Universidad,PONTIFICIA UNIVERSIDAD CATOLICA DEL PERU,SEDE SAN MIGUEL,ARQUITECTURA,REGISTRO COMPLETO,2016-08,2016-08,2017-01,LOS OLIVOS,14/04/2026 14:01:19
2,4,1era. convocatoria,Universidad,PONTIFICIA UNIVERSIDAD CATOLICA DEL PERU,SEDE SAN MIGUEL,INGENIERIA CIVIL,REGISTRO COMPLETO,2016-02,2015-12,2016-02,CAJAMARCA,14/04/2026 14:01:19
3,5,2da. convocatoria,Universidad,PONTIFICIA UNIVERSIDAD CATOLICA DEL PERU,SEDE SAN MIGUEL,INGENIERIA CIVIL,REGISTRO COMPLETO,2016-08,2016-08,2017-01,CALLAO,14/04/2026 14:01:19
4,6,2da. convocatoria,Universidad,PONTIFICIA UNIVERSIDAD CATOLICA DEL PERU,SEDE SAN MIGUEL,INGENIERIA CIVIL,REGISTRO COMPLETO,2016-09,2016-08,2016-09,BELLAVISTA,14/04/2026 14:01:19

In [19]:

print("Este es el df5 -> Credito18EvaluacionSolicitud.csv")

df5 = safe_read_csv("datos_raw/personas/Credito18EvaluacionSolicitud.csv")
df5.head()
# Convocatoria,TipoInstitucion,InstitucionEducativa,InstitucionSede,Descripcion,EstadoCredito18,Periodo_Postulacion,Period_registro_postulac,Period_anulacion,UbigeoLocalidad,FECHA_HORA

Este es el df5 -> Credito18EvaluacionSolicitud.csv

,1,2da. convocatoria,Universidad,PONTIFICIA UNIVERSIDAD CATOLICA DEL PERU,SEDE SAN MIGUEL,ARQUITECTURA,REGISTRO COMPLETO,2016-08,2016-08.1,2017-01,LOS OLIVOS,14/04/2026 14:01:21
0,2,1era. convocatoria,Universidad,PONTIFICIA UNIVERSIDAD CATOLICA DEL PERU,SEDE SAN MIGUEL,ARQUITECTURA,REGISTRO COMPLETO,2016-01,2016-01,NaN,CALLAO,14/04/2026 14:01:21
1,3,2da. convocatoria,Universidad,PONTIFICIA UNIVERSIDAD CATOLICA DEL PERU,SEDE SAN MIGUEL,ARQUITECTURA,REGISTRO COMPLETO,2016-08,2016-08,2016-08,BREÑA,14/04/2026 14:01:21
2,4,2da. convocatoria,Universidad,PONTIFICIA UNIVERSIDAD CATOLICA DEL PERU,SEDE SAN MIGUEL,INGENIERIA CIVIL,EN PROCESO DE REGISTRO,NaN,2016-08,NaN,NaN,14/04/2026 14:01:21
3,5,1era. convocatoria,Universidad,PONTIFICIA UNIVERSIDAD CATOLICA DEL PERU,SEDE SAN MIGUEL,INGENIERIA CIVIL,REGISTRO COMPLETO,2016-02,2016-01,2016-02,LOS OLIVOS,14/04/2026 14:01:21
4,6,1era. convocatoria,Universidad,PONTIFICIA UNIVERSIDAD CATOLICA DEL PERU,SEDE SAN MIGUEL,INGENIERIA CIVIL,REGISTRO COMPLETO,2016-01,2015-12,NaN,LOS OLIVOS,14/04/2026 14:01:21

In [20]:

print("Este es el df6 -> Credito18DatosSolicitante.csv")

df6 = safe_read_csv("datos_raw/personas/Credito18DatosSolicitante.csv")
df6.head()
#Id_Persona,Convocatoria,EstudianteTipo,FamiliarTipo,TieneTelefonoFijo,TieneTelefonoCelular,TieneEmail,Ingresos_Mensuales,Gastos_Mensuales,Fecha_Registro,TieneFichaSocioeconomica,Genero,NacimientoUbigeo,FECHA_HORA

Este es el df6 -> Credito18DatosSolicitante.csv

,1,PD1zq,1era. convocatoria,Unnamed: 3,PADRE,Tiene,Tiene.1,Tiene.2,200,200.1,2015-11,Tiene.3,FEMENINO,CALANA,14/04/2026 14:01:19
0,2,Rqm8,NaN,NaN,PADRE,No Tiene,No tiene,No Tiene,1650.0,NaN,2020-03,Tiene,MASCULINO,CARMEN DE LA LEGUA REYNOSO,14/04/2026 14:01:19
1,3,QDWGz,1era. convocatoria,NaN,PADRE,No Tiene,No tiene,No Tiene,1800.0,NaN,2021-08,Tiene,FEMENINO,JESUS MARIA,14/04/2026 14:01:19
2,4,V0A3m,1era. convocatoria,NaN,PADRE,Tiene,Tiene,sdsd,3000.0,2000,2015-11,Tiene,NaN,NaN,14/04/2026 14:01:19
3,5,K2pQv,1era. convocatoria,NaN,PADRE,No Tiene,Tiene,No Tiene,2400.0,2300,2015-12,Tiene,MASCULINO,SANTIAGO DE SURCO,14/04/2026 14:01:19
4,6,7bjEe,1era. convocatoria,NaN,PADRE,Tiene,Tiene,No Tiene,1700.0,1500,2015-12,Tiene,NaN,NaN,14/04/2026 14:01:19

In [21]:

print("Este es el df7 -> NotasDeBecarios_Top200.csv")
df7 = safe_read_csv("datos_raw/personas/becados/NotasDeBecarios_Top200.csv")
df7.head()

# Postulacion, Semestre, Ciclo, Nota(enteros), Nota(decimales_que_se_suman _a_enteros), FECHA_HORA

Este es el df7 -> NotasDeBecarios_Top200.csv

   1  LMqR  2012-II      PRIMER CICLO  16  43  14/04/2026 15:27:04
0  2  pNgl  2012-II  CICLO NIVELACION  13  80  14/04/2026 15:27:04
1  3  pNgl   2013-I      PRIMER CICLO  13  31  14/04/2026 15:27:04
2  4  ndZ7  2012-II      PRIMER CICLO  15  37  14/04/2026 15:27:04
3  5  ndZ7   2013-I     SEGUNDO CICLO  14  51  14/04/2026 15:27:04
4  6  ndZ7  2013-II      TERCER CICLO  15  33  14/04/2026 15:27:04

In [22]:

print("Este es el df8 -> Convocatorias.csv")
df8 = safe_read_csv("datos_raw/becas/Convocatorias.csv")
df8.head()

#Id_Convocatoria, Codigo_anual_convocat, Descripcion, Modalidad_Descripcion, Programa_Descripcion, Becas_ofertadas, TipoLimiteEdad, Fec_LimiteEdad, Fec_Ini_Inscripcion, Fec_Fin_Inscripcion, Fec_Ini_Evaluacion, Fec_Fin_Evaluacion, Fec_Ini_Ejecucion, Fec_Fin_Ejecucion, RangoEdadInicio, RangoEdadFin, RJ_Aprobacion, FECHA_HORA

Este es el df8 -> Convocatorias.csv

,1,23,2013-02,Beca Excelencia para estudios de Postgrado en el Extranjero,Beca Generación del Bicentenario (anteriormente denominada Beca Presidente de la República),Becas Postgrado Extranjero,400,Unnamed: 7,31/12/2013,25/11/2012,15/02/2013,16/02/2013,27/02/2013,11/10/2012,11/10/2012.1,0,45,RDE N° 126-2012-PRONABEC-OBEC-VMGI-MED,14/04/2026 14:01:22
0,2.0,3,2012-01,Beca Perú,Beca Peru,Beca Peru,720.0,2.0,NaN,15/07/2012,13/09/2012,01/09/2012,01/10/2012,01/01/2012,30/12/2012,15.0,40.0,RDE N° 056-2012-PRONABEC-OBEC-VMGI-MED,14/04/2026 14:01:22
1,3.0,10,2013-01,Beca 18 Internacional - Cuba,Modalidad Pregrado Internacional,Becas Cuba,100.0,2.0,01/12/2012,28/09/2012,20/12/2012,01/07/2012,31/07/2012,01/08/2012,01/09/2012,17.0,23.0,RDE N° 091-2012-PRONABEC-OBEC-VMGI-MED,14/04/2026 14:01:22
2,4.0,12,2012-02,Beca 18 FFAA (2da Convocatoria),Licenciados FFAA,Beca FFAA,NaN,2.0,NaN,26/07/2012,07/12/2012,26/07/2012,09/08/2012,25/07/2012,11/08/2012,16.0,26.0,NaN,14/04/2026 14:01:22
3,5.0,13,2012-01,Beca 18 VRAEM,VRAEM,Beca VRAEM,500.0,1.0,30/12/2012,26/07/2012,22/09/2012,26/07/2012,09/08/2012,25/07/2012,29/08/2012,15.0,23.0,RDE N° 047-2012-PRONABEC-OBEC-VMGI-MED,14/04/2026 14:01:22
4,6.0,16,2012,Beca 18 Modalidad Ordinaria,Modalidad Ordinaria,Beca Ordinario,2950.0,2.0,NaN,01/01/2012,31/05/2012,20/04/2012,31/05/2012,20/04/2012,31/05/2012,15.0,23.0,RM N° 080-2012-ED,14/04/2026 14:01:22

In [23]:

print("Este es el df9 -> ConvocatoriaPorCarreraSede_Top200.csv")


df9 = safe_read_csv("datos_raw/becas/ConvocatoriaPorCarreraSede_Top200.csv")
df9.head()

# Id_Convocatoria, ConvocatoriaDescripcion, PaisOrigen, NivelEducativo, TipoInstitucion, SedeNombre, Nombre, CarreraDescripcion, Resolucion_Autoriza, TipoDeGestion, Abreviatura, Region,DireccionWeb, Representante, Telefono, Ruc, Email, FECHA_HORA

Este es el df9 -> ConvocatoriaPorCarreraSede_Top200.csv

,1,139,Beca Alianza del Pacífico (extranjeros en el Perú),PERU,Carrera Universitaria,Universidad,SEDE TARAPOTO,UNIVERSIDAD CESAR VALLEJO S.A.C.,TRADUCCION E INTERPRETACION,Unnamed: 9,PRIVADA,UNIV,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,20164113532,Unnamed: 17,14/04/2026 15:59:23
2,140,Beca Alianza del Pacífico (Peruanos en el extr...,MEXICO,Carrera Universitaria,Instituto,SEDE PUEBLA,INSTITUTO NACIONAL DE ASTROFISICA,OPTICA Y ELECTRONICA (INAOE),GENERICA,NaN,PÚBLICA,INS,NaN,NaN,NaN,NaN,NaN,NaN,14/04/2026 15:59:23
3,140,Beca Alianza del Pacífico (Peruanos en el extr...,MEXICO,Carrera Universitaria,Universidad,SEDE SAN PEDRO GARZA GARCIA,UNIVERSIDAD DE MONTERREY (UDEM),GENERICA,NaN,PRIVADA,UNIV,NaN,NaN,NaN,NaN,NaN,NaN,14/04/2026 15:59:23,None
4,389,Crédito Talento - Convocatoria 2023,PERU,Carrera Universitaria,Universidad,SEDE LURIGANCHO - CHOSICA,UNIVERSIDAD PERUANA UNION,INGENIERIA DE SISTEMAS,RDE 090-2023-MINEDU/VMGI-PRONABEC,PRIVADA,UNIV,NaN,NaN,NaN,NaN,2.013812e+10,NaN,14/04/2026 15:59:23,None
5,389,Crédito Talento - Convocatoria 2023,PERU,Carrera Universitaria,Universidad,SEDE CUSCO,UNIVERSIDAD TECNOLOGICA DE LOS ANDES,ENFERMERIA,RDE 090-2023-MINEDU/VMGI-PRONABEC,PRIVADA,UNIV,NaN,NaN,NaN,NaN,2.010499e+10,emamanic@utea.edu.pe,14/04/2026 15:59:23,None
6,389,Crédito Talento - Convocatoria 2023,PERU,Carrera Universitaria,Universidad,SEDE LURIGANCHO - CHOSICA,UNIVERSIDAD PERUANA UNION,ENFERMERIA,RDE 090-2023-MINEDU/VMGI-PRONABEC,PRIVADA,UNIV,NaN,NaN,NaN,NaN,2.013812e+10,NaN,14/04/2026 15:59:23,None

1.- Items a recomendar
CSVs: ConvocatoriaPorCarreraSede_Top200.csv (df9) y Convocatorias.csv (df8).

Explicación: df9 detalla carreras e instituciones, mientras df8 aporta límites de edad y tipo de beca. Juntos forman el catálogo exacto de opciones a evaluar.

2.- Usuario
CSVs: Credito18DatosSolicitante.csv (df6) y Credito18Postulacion.csv (df4).

Explicación: df6 define el perfil socioeconómico (ingresos, ubicación), mientras df4 muestra la intención académica (carrera/universidad). Son los datos de entrada para tu motor concurrente.

3.- El historial de quién ganó qué
Como los datos están anonimizados para proteger la identidad, tienes dos opciones válidas para implementar el cruce:

Opción A (Cruce Directo por Reglas):

CSVs: df6 (Usuario) + df8 y df9 (Becas).

Explicación: Las goroutines cruzan directamente los ingresos y ubicación del estudiante (df6) con los requisitos de la beca (df8, df9). No depende del historial pasado.

Opción B (Historial de Éxito / Predictivo):

CSVs: df4 (Postulaciones) + df7 (NotasDeBecarios_Top200.csv).

Explicación: Usas df4 para ver a dónde postularon y cruzas con df7 porque solo los ganadores reales generan registros de notas, sirviendo como tu historial de éxito.

<!-- 1.- Items a recomendar
CSVs: ConvocatoriaPorCarreraSede_Top200.csv (df9) y Convocatorias.csv (df8).

Explicación: df9 detalla carreras e instituciones, mientras df8 aporta límites de edad y tipo de beca. Juntos forman el catálogo exacto de opciones a evaluar.

2.- Usuario
CSVs: Credito18DatosSolicitante.csv (df6) y Credito18Postulacion.csv (df4).

Explicación: df6 define el perfil socioeconómico (ingresos, ubicación), mientras df4 muestra la intención académica (carrera/universidad). Son los datos de entrada para tu motor concurrente.

3.- El historial de quién ganó qué
Como los datos están anonimizados para proteger la identidad, tienes dos opciones válidas para implementar el cruce:

Opción A (Cruce Directo por Reglas):

CSVs: df6 (Usuario) + df8 y df9 (Becas).

Explicación: Las goroutines cruzan directamente los ingresos y ubicación del estudiante (df6) con los requisitos de la beca (df8, df9). No depende del historial pasado.

Opción B (Historial de Éxito / Predictivo):

CSVs: df4 (Postulaciones) + df7 (NotasDeBecarios_Top200.csv).

Explicación: Usas df4 para ver a dónde postularon y cruzas con df7 porque solo los ganadores reales generan registros de notas, sirviendo como tu historial de éxito. -->

Lo que tengo planeado: 
1.- Multiplicar los datos necesarios.

2.- Cambiar nombre las columnas de los csv necesarios.

3.- Hacer limpieza de datos (valores nulos, eliminar columnas innecesarias)

CON ESO YA ESTARÍAMOS PARA LA PC